version: '3.8'

networks:
  transcendance:

    #volumes:
    #  dbv:
    #    driver: local
    #    driver_opts:
    #      type: none
    #      o: "bind"
    #      device: ${DBV_PATH}

    #  bv:
    #    driver: local
    #    driver_opts:
    #      type: none
    #      o: "bind"
    #      device: ${BV_PATH}

    #  fv:
    #    driver: local
    #    driver_opts:
    #      type: none
    #      o: "bind"
    #      device: ${FV_PATH}

services:

  front:
    build: ./front
    container_name: tr_front_cont
    restart: always
    volumes:
      - ./front:/transcendance
      - /transcendance/node_modules
    ports:
      - '3000:3000'

  back:
    build: ./back
    container_name: tr_back_cont
    restart: always
    networks:
      - transcendance
    volumes:
      - ./back:/transcendance
      - /transcendance/node_modules
    depends_on:
      - db
    ports:
      - '3333:3333'
      - '5555:5555'

  db:
    image: postgres
    container_name: tr_db_cont
    restart: always
    networks:
      - transcendance
    volumes:
      - ./database:/transcendance
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTG_PWD}
      POSTGRES_USER: ${POSTG_USR}
      POSTGRES_DB: ${POSTG_DB}

  adminer:
    image: adminer
    container_name: tr_adminer_cont
    networks:
      - transcendance
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
